root: true
extends:
  - plugin:@typescript-eslint/recommended
plugins:
  - simple-import-sort
rules:
  'no-console': ['warn']
  'simple-import-sort/imports': ['error']
  'simple-import-sort/exports': ['error']
  'import/order': ['off']
  'sort-imports': ['off']
  'no-await-in-loop': ['error']
  'no-invalid-this': ['error']
  'no-param-reassign': ['error']
  '@typescript-eslint/explicit-function-return-type': ['error']
overrides:
  - files:
      - '**/*.test.ts'
    rules:
      '@typescript-eslint/no-non-null-assertion': ['off']
